<div class="container-fluid no-padding banner-carousel">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="owl-carousel owl-theme" id="banner-slider">
                        <div class="item">
                            <div class="sliderimg" style="background-image:url(<?php echo $this->getViewFileUrl('IFlair_LahrerladenHomeSlider::images/Sliderbild.png');?>);">
                            </div>
                        </div>
                        <div class="item">
                            <div class="sliderimg" style="background-image:url(<?php echo $this->getViewFileUrl('IFlair_LahrerladenHomeSlider::images/Sliderbild.png');?>);">
                            </div>
                        </div>
                        <div class="item">
                            <div class="sliderimg" style="background-image:url(<?php echo $this->getViewFileUrl('IFlair_LahrerladenHomeSlider::images/Sliderbild.png');?>);">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
<?php
	//echo $block->sayHello();